add_lunch_combo evolution_d2vzw-userdebug
add_lunch_combo evolution_grouper-userdebug
add_lunch_combo evolution_i605-userdebug
add_lunch_combo evolution_maguro-userdebug
add_lunch_combo evolution_t0lte-userdebug
add_lunch_combo evolution_toro-userdebug
